### ISSUE TITLE
Addnodes

### ISSUE THREAD

**Issue by le2Ks** [MyoThuHtay/MOPS-COIN#1]
Hi, any addnodes to connect to the blockchain's network? Thanks!

**Comment by MyoThuHtay** [comment]
Sorry, just now i just testing in my local and not satisfied yet. But there will be soon and thank you for interested.

**Comment by MyoThuHtay** [comment]
you can connect to the Blockchain now.

**Comment by le2Ks** [comment]
Hello, thanks for replying.

# NODES
Could you double check again pls because the addnodes:
mainnet-seed1.mopschain.site
mainnet-seed2.mopschain.site
mainnet-seed3.mopschain.site

are hidden being a proxy provided by CloudFlare. By doing so, it is impossible for the wallet to connect to the nodes. They have to be set to "DNS ONLY" otherwise it won't be possible for the wallet to find the nodes' ip addresses.

I've also tried to connect with the hex decimal coded ip addresses from net.cpp, that gave the following results:
```
0xf495bdce -> 244.149.189.206
0x7ffcff36 -> 127.252.255.54
0x857669ac -> 133.118.105.172
```

but still didn't work. Even tried the opposite, so:
```
206.189.149.244
54.255.252.127
172.105.118.133
```
 in case they would have been incorrectly typed in the code, but didn't work either.
Perhaps the P2P port "6464" hasn't been opened yet from the nodes' servers.


 # EXPLORER
Also, but this is not related to the nodes, you may have to check the block explorer https://explorer.mopschain.site/ that is giving a SSL error from CloudFlare (see attached image)
<img width="300"  src="https://i.imgur.com/YUlGxtt.png">


Thank you
