### ISSUE TITLE
Nodes

### ISSUE THREAD

**Issue by le2Ks** [MyoThuHtay/MOPS-COIN#4]
Hello, the following addnods, mentioned in the code, do not seem to be available:
```
seed1.mopschain.site
seed2.mopswalletcore.site
```
Could you please double check if they are online? Thank you.

**Comment by MyoThuHtay** [comment]
hi sorry for late reply, seed1.mopschain.site now available

**Comment by le2Ks** [comment]
> hi sorry for late reply, seed1.mopschain.site now available

Hello, tried to but it  still won't connect. Could you please double check
